---
title: "Academic Policies"
---

## EXAM & HOMEWORK POLICY

Without prior arrangement, there will be no extensions or make-ups without penalty except in instances such as the following:

-   hospitalization or illness that has been documented and judged by your instructor as preventing you from a) preparing adequately for an exam or quiz or b) completing an assignment
-   death or serious illness in your family
-   court appearances
-   religious observances

Documentation must be provided by health officials (e.g., a physician or member of the student health center staff) in the case of illness; an immediate family member in the case of death or serious illness in the family; and official paperwork in the case of court dates. Decisions regarding extensions and make-ups under these circumstances will be made on a case-by-case basis. In general, quizzes are not eligible for make-up work; instead, your two lowest quiz grades are automatically dropped. Lab homework is penalized at 5% per day for late submission (i.e., starting when lab time begins) and receives no credit if it is submitted over a week late. When possible, I encourage students to reach out as soon as you know that you may miss class and/or related work; it is much easier to develop a plan in advance than it is to do so later.

## ACADEMIC INTEGRITY & HONOR CODE

All students in this course are to become familiar with and follow the University’s honor code, which does not tolerate any form of cheating and attempted cheating, plagiarism, lying, and stealing. Exams and assignments are expected to be individual efforts unless otherwise noted by the instructor or teaching assistant. Violations of the GMU Honor Code can result in failure of an assignment or exam, depending on the severity of violation. All violations will be reported to the Honor Committee. The instructor for this course reserves the right to enter a failing grade to any student found guilty of an honor code violation. For more information on the Honor Code please [visit this webpage](https://oai.gmu.edu/mason-honor-code/full-honor-code-document/ "GMU Honor Code").

## ACCOMMODATION OF DISABILITIES

Disability Services at George Mason University is committed to providing equitable access to learning opportunities for all students by upholding the laws that ensure equal treatment of people with disabilities. Note that this provision includes the range of disabilities, including physical, psychiatric, and learning disabilities. If you are seeking accommodations for this class, please first [visit here](http://ds.gmu.edu/) for detailed information about the Disability Services registration process. Then please discuss your approved accommodations with me. All academic accommodations must be arranged through Disability Services. Disability Services is located in Student Union Building I (SUB I), Suite 2500. Email: ods\@gmu.edu \| Phone: (703) 993 – 2474.

## SEXUAL HARASSMENT, SEXUAL MISCONDUCT, AND INTERPERSONAL VIOLENCE

As a faculty member and designated “Responsible Employee,” I am required to report all disclosures of sexual assault, interpersonal violence, and stalking to Mason’s Title IX Coordinator per university policy 1412. If you wish to speak with someone confidentially, please contact the Student Support and Advocacy Center (703-380-1434) or Counseling and Psychological Services (703-993-2380). You may also seek assistance from Mason’s Title IX Coordinator (703-993-8730; titleix\@gmu.edu).

## STUDENT SUPPORT SERVICES

George Mason offers services to support students’ academic and emotional development. Counseling and Psychological Services, located in SUB I room 3129 (caps.gmu.edu), offers workshops in academic skills, stress management training, and virtual counseling for students who would like some help with social, emotional, or educational concerns. Consider taking advantage of these resources if you need them. For additional information about other student support services offered, please visit the [Stearns Center Knowledge Center](https://stearnscenter.gmu.edu/knowledge-center/knowing-mason-students/student-support-resources-on-campus/).
