---
title: "Instructional Resources"
bibliography: references.bib
---

The 2024 academic year brings some change to my previous format. Instead of focusing on the text and abiding by the author's train of thought, I opted for a more efficient course that focuses on projects and "just in time" learning. You will need to read and if you are efficient, you may be able to read two texts in one semester. The requirement, however, is to read one of the following books:

## OPTION 1: Gentler introduction to Bayesian statistics

**Kurt, W. (2019). *Bayesian statistics the fun way: Understanding statistics and probability with Star Wars, Lego, and Rubber Ducks*. No Starch Press.**

@kurt2018 provides a thorough and accurate rundown of most Bayesian principles in an engaging style. I chose this book as one to replace my next and favorite book to enable students to better grasp the big picture rather than get bogged down in details. The reviews of Kurt's book are quite favorable (see [@perezgonzalez2020]). From my angle, there are pros and cons of relying on Kurt's book as an introduction to Bayesian statistics.

::: {.callout-note collapse="true" title="PROS and CONS of Kurt's book"}
**PROS** 1. Gentle introduction to Bayesian statistics 2. Shorter weekly reading assignments 3. Engaging style 4. Covers most of the material in the course 5. Provides a good foundation for the more technical book

**CONS** 1. Does not delve into the technical details much 2. Longer weekly requirements for the assignments 3. Avoids the math that may be essential to your understanding 4. Lack of coding examples may be a problem for some
:::

There are resources available for the book, including [code](https://github.com/willkurt/ProbAndStats-PyDataNYC2019) and [notes from others](https://bookdown.org/pbaumgartner/bayesian-fun/).  Please consult the [book's website](https://nostarch.com/learnbayes) for more information.

## OPTION 2: A more technical introductory test

**McElreath, R.M. (2020). Statistical rethinking: A Bayesian course with examples in R and Stan, 2nd Ed. Chapman & Hall/CRC Press. Boca Raton, FL. (ISBN: 978-0-429-02960-8)**

@mcelreath2020 gives us one of the most accessible, technical books on applied Bayesian analysis - all from a social scientist's perspective. He wrote an engaging book that digs deep enough into the material to give you some real insights but also pushes you to learn the code. For the mathematically oriented reader, you will be disappointed; the coders among us will enjoy his blend of conceptual and computational material. McElreath does not delve into the math, but he does provide a good foundation for the more technical books. The reviews of McElreath's book are beyond favorable (see [@kelter2020]) and many of us have used his book for the past few years. So, if all the positive press and favorable reviews, why am I suggesting this book as my second of two? There are several reasons but to give you the bottom line, I think the book is too ambitious for a single semester course. Instead, I think Bayesian statistics ought to be a two-semester course that divides probability theory and programming into a first-semester course followed by this book. More on that later.

## Course website

The [course website](https://sites.google.com/view/gmupsyc757/home) contains tons of videos, links, and resources for the course.  Slowly, I am transitioning away from Google Sites and towards this website and GitHub in general.  Most of the links will be ported over here to the syllabus.  The course website will remain active for the foreseeable future.  Do use it.

## References

::: {#refs}

:::


